--CHECK TABLE PARTITIONS
SET LINES 1000 PAGES 1000 COLSEP | 
COLUMN table_owner FORMAT a13
COLUMN table_name FORMAT a30
COLUMN partition_name FORMAT a15
COLUMN high_value FORMAT a85
COLUMN tablespace_name FORMAT a20
SELECT TABLE_OWNER,TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME 
FROM DBA_TAB_PARTITIONS 
WHERE TABLE_OWNER = 'MBOSIUSR_OFFLINE'
AND TABLE_NAME IN ('MB_AUDIT_OFFLINE','MB_DAILY_SYNC_LOGS_OFFLINE','API_LOG_OFFLINE') 
ORDER BY TABLE_NAME, PARTITION_NAME;

